HomeWork
DimaZaitsau/SouceDemo2.0_QA22_Dima_Zaytsev pull request #1
Opened 2022-12-12 16:12 UTC by DimaZaitsau

2022-12-12 17:47 UTC, voropa requested changes

2022-12-12 17:47 UTC, voropa commented on README.md
> +1. Ввести username
В тест-кейсах или чеклистах должны фигурировать проверки какие-то, а у вас просто набор шагов

2022-12-12 17:47 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +    private final static By ADD_TO_CART_BUTTON = By.id("add-to-cart-sauce-labs-backpack");
Плохой локатор, так как он привязан к конкретному товару. Что если вы откроете эту страницу не для sauce-labs-backpack, а другого товара?

2022-12-12 17:47 UTC, voropa commented on src/test/java/tests/BasketTests.java
> +        basketPage.getItemName(testItemName);
Зачем вы выполняете это действие тут и не сохраняете результат ни в какую переменную? Фактически эта строчка когда ничего не делает

2022-12-12 17:47 UTC, voropa commented on src/test/java/tests/BasketTests.java
> +        basketPage.getItemDescription(testItemName);
То же самое

2022-12-12 17:47 UTC, voropa commented on src/test/java/tests/BasketTests.java
> +        try {
Ассерты не должны обрабатываться в try / catch, на то они и нужны, чтобы тест падал, если ассерт не проходит

2022-12-12 17:47 UTC, voropa commented on src/test/java/tests/BasketTests.java
> +        driver.getWindowHandle();
В тестах не должно быть явного испольщзования driver и его методов. Все действия должны быть с использованием page-классов. Там же на странице вроде есть кнопка "back" или "cancel", вот можно ее наживать

2022-12-12 17:47 UTC, voropa commented on src/test/java/tests/CheckoutOverviewTests.java
> +        driver.getWindowHandle();
То же самое с навигацией тут

2022-12-12 17:48 UTC, voropa commented
добавьте все файлы из папки .idea в .gitignore, они не должны попадать в комиты

2022-12-13 15:37 UTC, DimaZaitsau commented on src/test/java/pages/ItemPage.java
> +    private final static By ADD_TO_CART_BUTTON = By.id("add-to-cart-sauce-labs-backpack");
Поправил на private final static By ADD_TO_CART_BUTTON = By.className("btn btn_primary btn_small btn_inventory");

2022-12-15 18:06 UTC, voropa requested changes

2022-12-15 18:06 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +        driver.getWindowHandle();
для того, чтоюы сделать navigate.back() не нужно вызывать driver.getWindowHandle(). так что эта строчка тут лишняя

2022-12-20 06:48 UTC, voropa requested changes

2022-12-20 06:48 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    private final static By BURGER_BUTTON = By.cssSelector("#react-burger-menu-btn");
Вроде этиих кнопок нет на loginPage, они на других страницах находятся

2022-12-20 06:48 UTC, voropa commented on src/test/java/pages/Sotring.java
> +public class Sotring extends BasePage   {
Почему это у вас отдельная страница?
Это же просто выпадающий список на странице ProductsPage

2022-12-20 08:44 UTC, voropa commented on README.md
> +1. Ввести username
этот комментарий все еще актуален

2022-12-20 08:44 UTC, voropa commented on src/test/java/tests/BasketTests.java
> +        basketPage.getItemName(testItemName);
этот тоже

2022-12-22 19:57 UTC, voropa requested changes

2022-12-22 19:57 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    private final static By SELECT_A_TO_Z = By.xpath("//option[@value='az']");
ЗАачем ва м локаторы для этих options? Это же вырадающий список, с которым нужно работать через класс Select и у него есть методы selectValueByVisibleText / index/ value

2022-12-22 19:57 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    public ArrayList<String> sortListItemNameAToZ() {
А что делают эти методы и зачем они вам тут? 
у вас должен быть один метод, который возвращает список имен товаров в том виде, в котором он сейчас отображается на UI b и тест должен выглядеть ка-то так:
1. создаали expected список названий товаров
2. нажали на кнопку отсоритровать
3. получили список названий с UI
4. Сравнили с expected списком

2022-12-25 19:55 UTC, voropa approved these changes

2022-12-26 15:28 UTC, merged